### PR TITLE
Patch sharedpreference

### PR DESCRIPTION
**Pull request by SciFi1818**
This is a fix which will correct the sharedpreference bug.

### CODE REVIEW

**Comment by tiann** [comment]
Thanks for the bug fix, but the path should not be hard code, you'd better hook it in the android-hacker/exposed project.

**Comment by SciFi1818** [comment]
Okay I will look it

**Comment by SciFi1818** [comment]
Is it possible to call a Method in android-hacker/exposed project??  As it will make this repository no more standalone

**Comment by tiann** [comment]
You can add a method in this project and set the relative path, and call it from android-hacker/exposed; Keep the default behavior when the method is not called, because VAE can also run in root/Xposed environment.

If it is hard code, this project is not standalone too.

**Comment by SciFi1818** [comment]
Sorry to say that, I am not getting the exact idea of what to do....(may be due to my low experience)
I hope you can fix it soon ...

**Comment by tiann** [comment]
Thanks for issue the bug, I will fix it today.

**Pull request closed without merging**
